package main

import (
	"log"

	app "github.com/comfortablynumb/goginrestapi/internal/app"
)

// @title Users REST API
// @version 1.0
// @description This is an autogenerated Users REST API.

// @contact.name API Support

// @license.name MIT

// @host localhost:8080
// @BasePath /
func main() {
	application, err := app.NewAppFromEnv()

	if err != nil {
		log.Fatal(err)
	}

	err = application.Run()

	if err != nil {
		log.Fatal(err)
	}
}
