CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL,
    disabled TINYINT NOT NULL DEFAULT 0
    created_at DATETIME NOT NULL
    updated_at DATETIME NOT NULL
);