basePath: /
definitions:
  apperror.HttpError:
    properties:
      code:
        type: string
      data:
        additionalProperties: true
        type: object
      message:
        type: string
    type: object
  resource.UserCreateResource:
    properties:
      disabled:
        type: boolean
      user_type_name:
        type: string
      username:
        type: string
    required:
    - user_type_name
    - username
    type: object
  resource.UserDeleteResource:
    type: object
  resource.UserResource:
    properties:
      created_at:
        type: string
      disabled:
        type: boolean
      updated_at:
        type: string
      user_type:
        $ref: '#/definitions/resource.UserTypeResource'
        type: object
      username:
        type: string
    type: object
  resource.UserTypeCreateResource:
    properties:
      disabled:
        type: boolean
      name:
        type: string
    required:
    - name
    type: object
  resource.UserTypeResource:
    properties:
      created_at:
        type: string
      disabled:
        type: boolean
      name:
        type: string
      updated_at:
        type: string
    type: object
  resource.UserTypeUpdateResource:
    properties:
      disabled:
        type: boolean
    type: object
  resource.UserUpdateResource:
    properties:
      disabled:
        type: boolean
      user_type_name:
        type: string
    required:
    - user_type_name
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: This is an autogenerated Users REST API.
  license:
    name: MIT
  title: Users REST API
  version: "1.0"
paths:
  /user:
    get:
      description: Allows you to search for users using different filters and options.
      parameters:
      - description: Username
        in: query
        name: username
        type: string
      - description: 'Field to sort by. Allowed fields: username'
        in: query
        name: sort_by
        type: string
      - description: 'Direction to sort by. Allowed values: asc, desc. Default: asc'
        in: query
        name: sort_dir
        type: string
      - description: 'Starts results from this offset. Default: 0'
        in: query
        name: offset
        type: integer
      - description: 'Limits the amount of results to return. Default: 50'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.UserResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Search for users.
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Allows you to create a new user.
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/resource.UserCreateResource'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resource.UserResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Create a new user.
      tags:
      - users
  /user/{username}:
    delete:
      consumes:
      - application/json
      description: Allows you to delete an existing user.
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/resource.UserDeleteResource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.UserResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Delete a user.
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Allows you to update an existing user.
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/resource.UserUpdateResource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.UserResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Update a user.
      tags:
      - users
  /user_type:
    get:
      description: Allows you to search for user types using different filters and
        options.
      parameters:
      - description: User Type Name
        in: query
        name: name
        type: string
      - description: 'Field to sort by. Allowed fields: name'
        in: query
        name: sort_by
        type: string
      - description: 'Direction to sort by. Allowed values: asc, desc. Default: asc'
        in: query
        name: sort_dir
        type: string
      - description: 'Starts results from this offset. Default: 0'
        in: query
        name: offset
        type: integer
      - description: 'Limits the amount of results to return. Default: 50'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.UserTypeResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Search for user types.
      tags:
      - user types
    post:
      consumes:
      - application/json
      description: Allows you to create a new user type.
      parameters:
      - description: User Type data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/resource.UserTypeCreateResource'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resource.UserTypeResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Create a new user type.
      tags:
      - user types
  /user_type/{name}:
    delete:
      consumes:
      - application/json
      description: Allows you to delete an existing user type.
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.UserTypeResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Delete a user type.
      tags:
      - user types
    put:
      consumes:
      - application/json
      description: Allows you to update an existing user type.
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      - description: User Type data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/resource.UserTypeUpdateResource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.UserTypeResource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.HttpError'
      summary: Update a user type.
      tags:
      - user types
swagger: "2.0"
